server:
  port: 8189
  servlet:
    context-path: /school
    spring:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:shoolbase;MODE=PostgreSQL
        username: sa
        password:
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
